### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by LittleChest** [Andrews54757/MCObserver#2]
## Where is the source code of "https://minecraft-status-observer.herokuapp.com"?

In mainland China, it's too slow to cause inaccurate server latency, I want to create a mirror site to solve this problem.

**Comment by Andrews54757** [comment]
it is in the `server` folder.

**Comment by LittleChest** [comment]
After I import this code into Cloudflae Worker, the following message is displayed:

Uncaught ReferenceError: require is not defined at line 35 (Code: 10021)

what should I do? Or which service provider should I use to host it?
